[package]
name = "ambisonic"
version = "0.4.1"
authors = ["Martin Billinger <flkazemakase@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/mbillingr/ambisonic"
description = "Compose and play 3D audio."
readme = "README.md"
edition = "2018"

categories = ["multimedia", "multimedia::audio", "game-engines"]
keywords = ["audio", "ambisonics", "3D", "sound", "gamedev"]
include = ["src/**/*", "LICENSE-*", "README.md", "CHANGELOG.md"]

[dependencies]
cpal = ">=0.12, <=0.13"
rand = {version = "0.8", features = ["small_rng"]}
rand_distr = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rodio = ">=0.12, <=0.13"

[target.'cfg(target_arch = "wasm32")'.dependencies]
rodio = { version = ">=0.12, <=0.13", default-features = false, features = ["flac", "vorbis", "wav", "wasm-bindgen"] }
